=== AzizKhemiri/xml-scientific-library/schemas/bibliotheque.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- ISBN  -->
  <xs:simpleType name="TypeISBN">
    <xs:restriction base="xs:string">
      <xs:pattern value="97[89]-\d-\d{4}-\d{4}-\d"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Année -->
  <xs:simpleType name="TypeAnnee">
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="1900"/>
      <xs:maxInclusive value="2030"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Domaine -->
  <xs:simpleType name="TypeDomaine">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Informatique"/>
      <xs:enumeration value="WEB"/>
      <xs:enumeration value="Intelligence Artificielle"/>
      <xs:enumeration value="Réseaux"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Structure d'un livre -->
  <xs:element name="bibliotheque">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="livre" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="titre"  type="xs:string"/>
              <xs:element name="auteur" type="xs:string"/>
              <xs:element name="isbn"   type="TypeISBN"/>
              <xs:element name="annee"  type="TypeAnnee"/>
              <xs:element name="domaine" type="TypeDomaine"/>
            </xs:sequence>
            <xs:attribute name="id" type="xs:ID" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <!-- ISBN unique : deux livres ne peuvent pas avoir le même ISBN -->
    <xs:unique name="UniqueISBN">
      <xs:selector xpath="livre"/>
      <xs:field    xpath="isbn"/>
    </xs:unique>

  </xs:element>

</xs:schema>

=== AzizKhemiri/xml-scientific-library/data/catalogue.xml
<?xml version="1.0" encoding="UTF-8"?>
<bibliotheque
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="../schemas/bibliotheque.xsd">

  <livre id="L001">
    <titre>Intelligence Artificielle</titre>
    <auteur>Khadija Ben Abedkader</auteur>
    <isbn>978-2-1234-5678-9</isbn>
    <annee>2026</annee>
    <domaine>Intelligence Artificielle</domaine>
  </livre>

  <livre id="L002">
    <titre>Cloud &amp; DevOps</titre>
    <auteur>Aziz Khemiri</auteur>
    <isbn>978-2-7440-7441-8</isbn>
    <annee>2026</annee>
    <domaine>Informatique</domaine>
  </livre>

  <livre id="L003">
    <titre>Réseaux</titre>
    <auteur>Habib Youssef</auteur>
    <isbn>978-2-6789-0123-4</isbn>
    <annee>2026</annee>
    <domaine>Réseaux</domaine>
  </livre>

  <livre id="L004">
    <titre>Deep Learning</titre>
    <auteur>Lilia Chniti</auteur>
    <isbn>978-0-2625-3576-4</isbn>
    <annee>2026</annee>
    <domaine>Intelligence Artificielle</domaine>
  </livre>

  <livre id="L005">
    <titre>Developpement Full Stack</titre>
    <auteur>Fakher Sayeb</auteur>
    <isbn>978-2-5678-9012-3</isbn>
    <annee>2026</annee>
    <domaine>WEB</domaine>
  </livre>

</bibliotheque>
